# Generated by Django 5.0.3 on 2026-03-14 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_product_barcode'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
    ]
