# Generated by Django 5.0.3 on 2024-12-04 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_closedday_alter_dailysale_sale_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysale',
            name='closed_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.closedday'),
        ),
    ]
