# Generated by Django 5.0.3 on 2024-12-04 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_sale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.AddField(
            model_name='dailysale',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailysale',
            name='closed_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.closedday'),
        ),
    ]
