# Generated by Django 5.0.3 on 2024-12-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_delete_sale_dailysale_is_closed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysale',
            name='closed_day',
        ),
        migrations.AlterField(
            model_name='dailysale',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
