# Generated by Django 5.0.3 on 2024-12-04 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_dailysale_closed_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysale',
            name='closed_day',
        ),
    ]
