# Generated by Django 5.0.3 on 2026-03-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_customuser_managers_remove_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='Штрих-код или QR-код товара', max_length=100, null=True, unique=True, verbose_name='Баркод'),
        ),
    ]
